apiVersion: v1
kind: Service
metadata:
  name: enterprise-system-20260621-210214-gdwt5vwajoka-service
spec:
  selector:
    app: enterprise-system-20260621-210214-gdwt5vwajoka
  ports:
  - port: 80
    targetPort: 8000
  type: ClusterIP
